import './lib/consoleRuntime.js';
let l = [1, 2, 3];
let a = l.push(4);
let b = l.unshift(0);
let c = l.join(',');
let d = l.includes(2);
let e = l.indexOf(2);
let f = l.lastIndexOf(2);
let g = l.length;
let h = l.slice(0, 1);
let i = l.reverse();
let j = l.sort();
let k = l.concat([9]);
let m = l.flat();
let n = l.toSorted();
let ny = l.toReversed();
let p = l.pop();
let q = l.shift();
console.log(l);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);
console.log(k);
console.log(m);
console.log(n);
console.log(ny);
console.log(p);
console.log(q);
