import './lib/consoleRuntime.js';
let s = '  Hola  ';
let a = s.trim();
let b = s.split(' ');
let c = s.replace('a', 'b');
let d = s.replaceAll('a', 'b');
let e = s.endsWith('a');
let f = s.startsWith('a');
let g = s.repeat(2);
let h = s.slice(0, 1);
let i = s.toLowerCase();
let j = s.toUpperCase();
let k = s.includes('a');
let l = s.indexOf('a');
let m = s.lastIndexOf('a');
let n = s.charAt(0);
let ny = s.padStart(5, '0');
let p = s.padEnd(5, '0');
let q = s.concat('x');
let r = s.trimStart();
let t = s.trimEnd();
let u = s.normalize();
let v = s.search('a');
let w = s.charCodeAt(0);
let x = s.substring(0, 1);
let z = s.localeCompare('b');
let ab = s.length;
let ac = s.match('a');
let ad = s.matchAll('a');
console.log(s);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);
console.log(k);
console.log(l);
console.log(m);
console.log(n);
console.log(ny);
console.log(p);
console.log(q);
console.log(r);
console.log(t);
console.log(u);
console.log(v);
console.log(w);
console.log(x);
console.log(z);
console.log(ab);
console.log(ac);
console.log(ad);
