import './lib/consoleRuntime.js';
let m = new Map();
let a = m.has('a');
let b = m.delete('a');
let c = m.size;
let d = m.get('a');
let e = m.set('a', 1);
let cj = new Set();
let f = cj.add(1);
let r = new RegExp('a');
let g = r.test('a');
let h = r.exec('a');
console.log(m);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(cj);
console.log(f);
console.log(r);
console.log(g);
console.log(h);
