import './lib/consoleRuntime.js';
let n = 3;
let a = Number.isInteger(3);
let b = Number.isNaN(3);
let c = parseInt('3');
let d = parseFloat('3.5');
let e = n.toFixed(2);
let f = n.toPrecision(2);
let g = n.toString();
let h = Number.MAX_SAFE_INTEGER;
let i = Number.EPSILON;
console.log(n);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
