import path from "node:path";
import fs from "node:fs";

import { DisChordGenerator } from "../src/dischord/Generator/Generator";
import { KeyWords } from "../src/chord/KeywordsManager";
import { Lexer } from "../src/chord/Lexer";
import { DisChordParser } from "../src/dischord/Parser/Parser";
import { SymbolTable } from "../src/chord/SymbolsTable";
import { CodeProvider } from "../src/chord/CodeProvider";
import { DisChordASTNode, DisChordNodeType, DisChordTokenType } from "../src/dischord/types";
import { FileSystem } from "../src/utils/FileSystem";
import { CompilationContext } from "../src/cli/commands/CompileCommand";

/**
 * Base test class implementing the standard compilation pipeline execution.
 *
 * @class Test
 * @abstract
 */
export abstract class Test {
    /**
     * The name of the test case.
     *
     * @type {string}
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly name: string;

    /**
     * A brief description of what the test validates.
     *
     * @type {string}
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly description: string;

    /**
     * Absolute or relative path to the directory containing the test fixtures.
     *
     * @type {string}
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly fixturePath: string;

    /**
     * Flag indicating whether to override existing snapshot files with new outputs.
     */
    public forceUpdate: boolean = false;

    /**
     * Reads the raw input .chord file for this test.
     *
     * @type {string}
     * @protected
     * @throws {Error} If the file cannot be read.
     */
    protected get code(): string {
        const file = path.join(this.fixturePath, 'input.chord');
        return fs.readFileSync(file, 'utf-8');
    }

    /**
     * Reads the expected AST snapshot file.
     *
     * @type {string}
     * @protected
     * @throws {Error} If the file cannot be read.
     */
    protected get expectedAST(): string {
        const file = path.join(this.fixturePath, 'expected.ast.json');
        return fs.readFileSync(file, 'utf-8');
    }

    /**
     * Reads the expected generated JS file.
     *
     * @type {string}
     * @protected
     * @throws {Error} If the file cannot be read.
     */
    protected get expectedCode(): string {
        const file = path.join(this.fixturePath, 'expected.mjs');
        return fs.readFileSync(file, 'utf-8');
    }

    /**
     * Standard execution pipeline for tests.
     * Executes lexing, parsing, generation, and snapshot validation.
     * Subclasses can override this method if custom test behavior is required.
     *
     * @method run
     * @returns {void | Promise<void>}
     * @protected
     */
    protected run(): void | Promise<void> {
        const context: CompilationContext<DisChordNodeType> = {
            symbolTable: new SymbolTable(),
            keywordsManager: new KeyWords(),
            codeProvider: new CodeProvider(),
            projectRoot: FileSystem.configure(this.fixturePath).projectRoot
        };

        const fileName = path.basename(this.fixturePath);
        console.log(`Compilando: ${path.relative(context.projectRoot, fileName)}`);

        DisChordParser.registerGrammar(context);
        
        const code = this.code;
        context.codeProvider.currentCode = { name: fileName, content: code };
        
        const lexer = new Lexer<DisChordTokenType>(context);
        const tokens = lexer.tokenize();
        
        const parser = new DisChordParser(tokens, context);
        const ast: DisChordASTNode[] = parser.parse();
        
        const generator = new DisChordGenerator(context);
        const output = generator.generate(ast);

        const actualAstJson = JSON.stringify(ast, null, 2);
        this.assertOrUpdateSnapshot(actualAstJson, 'ast');
        this.assertOrUpdateSnapshot(output, 'code');
    }

    /**
     * Validates generated output against a snapshot, or automatically updates the file if required.
     *
     * @method assertOrUpdateSnapshot
     * @param {string} actualContent - Content generated by the compilation pipeline.
     * @param {'ast' | 'code'} snapshotType - Target snapshot fixture type to compare or update.
     * @param {boolean} [forceUpdate=false] - Optional override flag to force snapshot updating.
     * @returns {void}
     * @protected
     * @throws {Error} If comparison fails and not in snapshot update mode.
     */
    protected assertOrUpdateSnapshot(actualContent: string, snapshotType: 'ast' | 'code'): void {
        const targetFilename = snapshotType === 'ast' ? 'expected.ast.json' : 'expected.mjs';
        const targetPath = path.join(this.fixturePath, targetFilename);

        if (this.forceUpdate || !fs.existsSync(targetPath)) {
            fs.writeFileSync(targetPath, actualContent.trim() + '\n', 'utf-8');
            console.log(`[SNAPSHOT UPDATED] ${targetPath}`);
            return;
        }

        const expectedContent = snapshotType === 'ast' ? this.expectedAST : this.expectedCode;
        this.assertDeepEqual(actualContent, expectedContent);
    }

    /**
     * Asserts strict string match between actual result and expected snapshot.
     *
     * @method assertDeepEqual
     * @param {string} actual - The stringified value produced by the pipeline.
     * @param {string} expected - The expected outcome string.
     * @returns {void}
     * @protected
     * @throws {Error} Throws an assertion failure error if the processed strings do not match.
     */
    protected assertDeepEqual(actual: string, expected: string): void {
        const actualStr = JSON.stringify(actual.trim(), null, 2);
        const expectedStr = JSON.stringify(expected.trim(), null, 2);

        if (actualStr !== expectedStr) {
            throw new Error(
                `Assertion Failed\n` +
                `--- EXPECTED ---\n${expectedStr}\n` +
                `--- ACTUAL ---\n${actualStr}`
            );
        }
    }

    /**
     * Runner method to execute the test lifecycle wrapper.
     *
     * @method execute
     * @returns {Promise<boolean>} True if passed, false if failed.
     * @public
     */
    public async execute(): Promise<boolean> {
        try {
            await this.run();
            console.log(`[PASSED] ${this.name}: ${this.description}`);
            return true;
        } catch (error) {
            console.error(`[FAILED] ${this.name}: ${this.description}`);
            console.error(error instanceof Error ? error.stack : String(error));
            return false;
        }
    }
}