import { DisChordGenerator } from "../src/dischord/Generator/Generator";
import { KeyWords } from "../src/chord/KeywordsManager";
import { Lexer } from "../src/chord/Lexer";
import { DisChordParser } from "../src/dischord/Parser/Parser";
import { SymbolTable } from "../src/chord/SymbolsTable";
import { ASTNode, BaseNode, Token } from "../src/chord/types";
import { CodeProvider } from "../src/CodeProvider";
import { DisChordNode, DisChordNodeType, DisChordTokenType } from "../src/dischord/types";
import { FileSystem } from "../src/init/FileSystem";
import { CompilationContext } from "../src/init/Init";

/**
 * @class Test
 * @description Single-class test structure utilizing overrides and polymorphism for DisChord's pipeline.
 * @abstract
 */
export abstract class Test {
    /**
     * @type {string} The name of the test case.
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly name: string;

    /**
     * @type {string} A brief description of what the test validates.
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly description: string;

    /**
     * @type {string} The raw Chord source code input for the test pipeline.
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly code: string;

    /**
     * @type {string} The expected output string (AST snapshot, token list or generated code).
     * @public
     * @abstract
     * @readonly
     */
    public abstract readonly expected: string;

    /**
     * @method run
     * @description Contains the assertion and pipeline execution logic. Must be overridden by subclasses.
     * @returns {void | Promise<void>}
     * @public
     * @abstract
     */
    public abstract run(): void | Promise<void>;

    /**
     * @method createMockContext
     * @description Internal helper to abstract the CompilationContext building.
     * @param {string} code - Raw Chord source code to load into the context.
     * @returns {CompilationContext<DisChordNodeType>} The generated mock compilation context.
     * @protected
     */
    protected createMockContext(code: string): CompilationContext<DisChordNodeType> {
        const context: CompilationContext<DisChordNodeType> = {
            symbolTable: new SymbolTable(),
            keywordsManager: new KeyWords(),
            codeProvider: new CodeProvider(),
            projectRoot: FileSystem.configure(process.cwd()).projectRoot
        };

        context.codeProvider.currentCode = {
            name: this.name,
            content: code
        };

        DisChordParser.registerGrammar(context);

        return context;
    }

    /**
     * @method lex
     * @description Runs the Lexer phase over the provided code.
     * @param {CompilationContext<DisChordNodeType>} context - The compilation context to tokenize from.
     * @returns {Token<DisChordTokenType>[]} Array of tokens generated by the Lexer.
     * @protected
     */
    protected lex(context: CompilationContext<DisChordNodeType>): Token<DisChordTokenType>[] {
        return new Lexer(context).tokenize() as Token<DisChordTokenType>[];
    }

    /**
     * @method parse
     * @description Runs the Lexer and Parser phases to retrieve the AST body.
     * @param {Token<DisChordTokenType>[]} tokens - Array of tokens generated during the lexing phase.
     * @param {CompilationContext<DisChordNodeType>} context - The compilation context containing state and configs.
     * @returns {ASTNode<string, BaseNode<string>>[]} Array of AST Nodes.
     * @protected
     */
    protected parse(tokens: Token<DisChordTokenType>[], context: CompilationContext<DisChordNodeType>): ASTNode<string, BaseNode<string>>[] {
        return new DisChordParser(tokens, context).parse();
    }

    /**
     * @method generate
     * @description Placeholder for the Emitter/Generator phase. Should return the transpiled JS code string.
     * @param {ASTNode<DisChordNodeType, DisChordNode>[]} ast - The generated AST from the parser.
     * @param {CompilationContext<DisChordNodeType>} context - The compilation context containing state and configs.
     * @returns {string} Transpiled JavaScript/TypeScript output.
     * @protected
     */
    protected generate(ast: ASTNode<DisChordNodeType, DisChordNode>[], context: CompilationContext<DisChordNodeType>): string {
        return new DisChordGenerator(context).generate(ast);
    }

    /**
     * @method assertDeepEqual
     * @description Asserts strict string match between actual result and expected snapshot.
     * @param {string} actual - The stringified value produced by the pipeline.
     * @param {string} expected - The expected outcome string.
     * @returns {void}
     * @throws {Error} Throws an assertion failure error if the processed strings do not match.
     * @protected
     */
    protected assertDeepEqual(actual: string, expected: string): void {
        const actualStr = JSON.stringify(actual.trim(), null, 2);
        const expectedStr = JSON.stringify(expected.trim(), null, 2);

        if (actualStr !== expectedStr) {
            throw new Error(
                `Assertion Failed\n` +
                `--- EXPECTED ---\n${expectedStr}\n` +
                `--- ACTUAL ---\n${actualStr}`
            );
        }
    }

    /**
     * @method execute
     * @description Runner method to execute the test lifecycle wrapper.
     * @returns {Promise<boolean>} True if passed, false if failed.
     * @public
     */
    public async execute(): Promise<boolean> {
        try {
            await this.run();
            console.log(`[PASSED] ${this.name}: ${this.description}`);
            return true;
        } catch (error) {
            console.error(`[FAILED] ${this.name}: ${this.description}`);
            console.error(error instanceof Error ? error.stack : String(error));
            return false;
        }
    }
}