import './lib/consoleRuntime.js';
let f = new Date();
let ahora = Date.now();
let ms = Date.parse('2020-01-01');
let a = f.getFullYear();
let m = f.getMonth();
let d = f.getDate();
let h = f.getHours();
let t = f.getTime();
let iso = f.toISOString();
let s = f.toString();
let l = f.toLocaleString();
console.log(ahora);
console.log(ms);
console.log(a);
console.log(m);
console.log(d);
console.log(h);
console.log(t);
console.log(iso);
console.log(s);
console.log(l);
