import { ASTNode, BaseNode, TokenTypeUnion } from "../types";
import { Generator } from "./Generator";

/**
 * Base blueprint for all atomic node translators.
 * Mirroring the architectural pattern of SubParser.
 */
export abstract class SubGenerator<T extends string, N extends BaseNode<T>> {
    /**
     * @param parent - Reference to the main Generator orchestrator context.
     */
    constructor(protected parent: Generator<T, N>) {}

    /**
     * Abstract contract that forces every sub-generator to implement
     * its own AST-to-JS translation logic.
     * @param node - The specific AST node to transpile.
     * @returns {string} The resulting JavaScript code string.
     */
    public abstract visit(node: ASTNode<T, N>): string;

    /**
     * Whether `node`, generated by this SubGenerator, needs to be wrapped in parens when it's
     * visited in *statement* position (a top-level program node, or an entry in a
     * block/loop/condition/function body) rather than expression position (a value, a property, an
     * array element). Defaults to false — most node kinds render the same in both positions.
     * Overridden by SubGenerators whose output is only ambiguous in statement position (e.g. a
     * BDO rendering as `{ key: value }`, which JS parses as a block, not an object literal, unless
     * parenthesized as a statement).
     * @param node - The specific AST node about to be rendered as a statement.
     */
    public needsStatementParens(node: ASTNode<T, N>): boolean {
        return false;
    }
}

/**
 * Type utility representing the constructible signature of a SubGenerator class.
 */
export interface SubGeneratorClass<T extends string, N extends BaseNode<T>> {
    new (parent: Generator<T, N>): SubGenerator<T, N>;

    /** 
     * The token type string that triggers the activation of this specific sub-parser.
     */
    triggerToken: TokenTypeUnion<T> | undefined;
}