import './lib/consoleRuntime.js';
let a = Math.abs(1);
let b = Math.ceil(1.2);
let c = Math.pow(2, 3);
let d = Math.sqrt(4);
let e = Math.max(1, 2);
let f = Math.min(1, 2);
let g = Math.random();
let h = Math.sin(1);
let i = Math.PI;
let j = Math.E;
let k = Math.SQRT2;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);
console.log(k);
