export const symbols = {
    "{": "L_BRACE",
    "}": "R_BRACE",
    "(": "L_EXPRESSION",
    ")": "R_EXPRESSION",
    "[": "L_SQUARE",
    "]": "R_SQUARE",

    "=": "ES",
    "+": "MAS",
    "-": "MENOS",
    "*": "POR",
    "/": "ENTRE",
    "**": "EXP",
    "%": "RESTO",
    "?": "MAYOR",
    "¿": "MENOR",
    ">=": "MAYOR_IGUAL",
    "<=": "MENOR_IGUAL",
    "!": "no",
    "==": "igual_tipado",
    ";": "separador",
    ":": ":",
    ",": ",",
    ".": "."
} as any;