import { Token, TokenType, TokenTypeUnion } from '../../chord/types';
import { DisChordASTNode, DisChordNode, DisChordNodeType, DisChordTokenType } from '../types';

import { Parser } from '../../chord/Parser/Parser';
import { SubParserClass } from '../../chord/Parser/SubParser';
import { DisChordError, ErrorLevel } from '../../errors/ChordError';

import CommandParser from './Grammar/architectural/CommandParser';
import MessageParser from './Grammar/features/MessageParser';
import CollectorParser from './Grammar/features/CollectorParser';
import ClientParser from './Grammar/architectural/ClientParser';
import EventParser from './Grammar/architectural/EventParser';
import EmbedDeclarationParser from './Grammar/components/EmbedDeclarationParser';
import { CompilationContext } from '../../cli/commands/CompileCommand';
import DisChordStatementParser from './Grammar/DisChordStatementParser';

/**
 * Main Orchestrator for DisChord's syntactic analysis.
 * * This class extends the base Parser and delegates the responsibility of parsing 
 * specific structures (Messages, Commands, Events, etc.) to specialized sub-parsers 
 * using a composition-by-delegation pattern.
 */
export class DisChordParser extends Parser<DisChordNodeType, DisChordNode> {
    /**
     * Initializes a new instance of the DisChordParser.
     * @param tokens - The array of tokens generated by the Lexer.
     * @param current - The starting token index (defaults to 0).
     * @param context - The existing context to the DisChordParser.
     */
    constructor (
        tokens: Token<DisChordTokenType>[],
        context: CompilationContext<DisChordNodeType>,
        current: number = 0
    ) {
        super(tokens, current, context);
        this.registerInstances();
    }

    /**
     * Internal registry of specialized architectural sub-parsers.
     * @type {SubParserClass<DisChordNodeType, DisChordNode>[]}
     * @private
     * @readonly
     * @static
     */
    private static readonly DisChordSubParsers: SubParserClass<DisChordNodeType, DisChordNode>[] = [
        DisChordStatementParser,
        ClientParser,
        EventParser,
        CommandParser,
        MessageParser,
        CollectorParser
    ];

    /**
     * Injects DisChord-specific keywords into the global system 
     * so the Lexer can correctly identify them as tokens.
     * @override
     */
    static override registerGrammar (context: CompilationContext<DisChordNodeType>): void {
        DisChordParser.DisChordSubParsers.forEach(instance => {
            context.keywordsManager.extend(
                instance.keywords.reduce<Record<string, TokenTypeUnion<DisChordNodeType>>>((accumulator, keyword) => {
                    accumulator[keyword] = keyword as TokenTypeUnion<DisChordNodeType>;

                    return accumulator;
                }, {})
            );
        });

        super.registerGrammar(context);
    }

    /**
     * Binds instance-level routing tables for the injected SubParsers into the core execution context.
     * @override
     * @returns {void}
     */
    override registerInstances(): void {
        DisChordParser.DisChordSubParsers.forEach(instance => {
            this.register(instance);
        });

        super.registerInstances();
    }

    /**
     * Node types whose generator produces a whole, standalone module (a command or event file),
     * instead of contributing inline code to whatever file declares them. See `CommandVisitor`
     * and `EventVisitor` in the generator: each returns the *entire* content of its target file.
     * @private
     * @readonly
     */
    private static readonly WholeFileDeclarationTypes: DisChordNodeType[] = [
        DisChordTokenType.CREAR_COMANDO,
        DisChordTokenType.EVENTO
    ];

    /**
     * Parses the full token stream and validates that at most one whole-file declaration
     * (`comando`, `evento`) exists per file. Since the generator emits each one's entire
     * returned string as the file's content (compiled 1:1 from its source `.chord` file by
     * `CompileCommand`), a *second* one would produce a broken module (duplicate `export
     * default`, duplicate imports of the same name). Other top-level code (imports, reusable
     * classes, etc.) alongside a single whole-file declaration is fine — ES modules don't
     * require `import`/`export` to be textually first, so nothing about the generated output
     * actually breaks by mixing them.
     * @override
     * @returns {DisChordASTNode[]} The parsed top-level AST nodes.
     * @throws {DisChordError} If more than one whole-file declaration exists in the same file.
     */
    override parse(): DisChordASTNode[] {
        const nodes = super.parse();

        const wholeFileNodes = nodes.filter(node => DisChordParser.WholeFileDeclarationTypes.includes(node.type));

        if (wholeFileNodes.length > 1) throw new DisChordError({
            phase: ErrorLevel.Parser,
            message: `Solo se permite un 'comando' o 'evento' por archivo. Este archivo declara ${wholeFileNodes.length}: separalos en un archivo por cada uno.`,
            location: wholeFileNodes[1].location
        }).format();

        return nodes;
    }

    /**
     * Entry point for custom DisChord statements.
     * Analyzes top-level tokens such as 'encender', 'evento', etc.
     * @override
     * @returns The generated ASTNode or null if no match is found.
     */
    override parseCustomStatement(): DisChordASTNode | null {
        const token = this.peek();

        // 'embed' deliberately stays an unreserved identifier (see EmbedDeclarationParser), so
        // it can't be matched by the triggerToken dispatch below — it's matched by literal value
        // here instead, requiring the `<Nombre> {` shape so it can't be confused with 'embed'
        // used as an ordinary BDO property key elsewhere (e.g. inside `nuevo mensaje {}`).
        if (token.type === TokenType.IDENTIFICADOR && token.value === 'embed'
            && this.peek('next').type === TokenType.IDENTIFICADOR
            && this.peek(this.cursor + 2)?.type === TokenType.L_BRACE) {
            this.consume(TokenType.IDENTIFICADOR);
            return new EmbedDeclarationParser(this).parse();
        }

        const ParserClass = DisChordParser.DisChordSubParsers.find(SubParser =>
            SubParser.triggerToken !== undefined &&
            SubParser.triggerToken === token.type
        );

        if (ParserClass) return new ParserClass(this).parse();

        return null;
    }

    /**
     * Intercepts the statement parsing pipeline to inject the DisChordStatementParser middleware.
     * @override
     * @returns {DisChordASTNode} The processed syntax tree node.
     */
    override parseStatement(): DisChordASTNode {
        return this.get(DisChordStatementParser).parse();
    }
}