import { KeyWords } from '../../chord/keywords';
import { Token } from '../../chord/types';
import { DisChordASTNode, DisChordNode, DisChordNodeType, ODBNode } from '../types';

import { Parser } from '../../chord/parser';
import { SubParserClass } from './subparser';

import CommandParser from './Commands/CommandParser';
import MessageParser from './Messages/MessageParser';
import CollectorParser from './CollectorParser';
import ClientParser from './Client/ClientParser';
import EventParser from './Events/EventParser';

/**
 * Main Orchestrator for DisChord's syntactic analysis.
 * * This class extends the base Parser and delegates the responsibility of parsing 
 * specific structures (Messages, Commands, Events, etc.) to specialized sub-parsers 
 * using a composition-by-delegation pattern.
 */
export class DisChordParser extends Parser<DisChordNodeType, DisChordNode> {
    /**
     * The inventory of specialists.
     * Adding a class here will register it into the all system.
     */
    private static readonly SubParsers: SubParserClass[] = [
        ClientParser,
        EventParser,
        CommandParser,
        MessageParser,
        CollectorParser
    ];

    /**
     * Initializes a new instance of the DisChordParser.
     * @param tokens - The array of tokens generated by the Lexer.
     * @param current - The starting token index (defaults to 0).
     */
    constructor (tokens: Token[], current: number = 0) {
        super(tokens, current);
    }

    /**
     * Injects DisChord-specific keywords into the global system 
     * so the Lexer can correctly identify them as tokens.
     */
    public static injectStatements() {
        KeyWords.addStatements([ "crear" ]);

        this.SubParsers.forEach(SubParser => {
            SubParser.injectStatements();
        });
    }

    /**
     * Entry point for custom DisChord statements.
     * Analyzes top-level tokens such as 'encender', 'evento', or 'crear'.
     * @override
     * @returns The generated ASTNode or null if no match is found.
     */
    override parseCustomStatement(): DisChordASTNode | null {
        const token = this.peek();

        const ParserClass = DisChordParser.SubParsers.find(SubParser =>
            SubParser.triggerToken.toUpperCase() === token.type
        );

        if (ParserClass) return new ParserClass(this).parse();

        return null;
    }

    /**
     * Extends the base language's primary expressions.
     * Allows the 'crear' (create) keyword to be treated as a primary expression.
     * @override
     */
    override parsePrimary(): DisChordASTNode {
        const token = this.peek();

        switch (token.type) {
            case 'CREAR':
                return this.parseStatement();
            default:
                return super.parsePrimary();
        }
    }

    /**
     * Parses an ODB.
     * Distinguishes between property blocks (key-value pairs) and execution statements.
     * @returns {ODBNode} A node containing organized blocks and an executable body.
     */
    parseODB(): ODBNode {
        this.consume('L_BRACE');

        const blocks: Record<string, DisChordASTNode> = {};
        const body: DisChordASTNode[] = [];

        while (this.peek().type !== 'R_BRACE') {
            if (this.isPropertyAssignment()) {
                const key = this.consume('IDENTIFICADOR').value;

                const value = this.parsePrimary();
                blocks[key] = value;
            } else {
                const statement = this.parseStatement();
                if (statement) body.push(statement);
            }
        }

        this.consume('R_BRACE');

        return {
            type: 'BDO',
            blocks,
            body
        };
    }

    /**
     * Predicate to distinguish between a property assignment and a statement.
     * Looks a token forward to decide.
     */
    private isPropertyAssignment(): boolean {
        const current = this.peek();
        const next = this.peek();

        if (current.type !== 'IDENTIFICADOR') return false;

        if (next.type === 'R_BRACE') return false;

        const reservedStatements = ['var', 'crear', 'si', 'bucle', 'esperar', 'retornar', 'encender'];
        if (reservedStatements.includes(current.value)) return false;

        return true; 
    }
}