import { Token, TokenTypeUnion } from '../../chord/types';
import { DisChordASTNode, DisChordNode, DisChordNodeType, DisChordTokenType } from '../types';

import { Parser } from '../../chord/Parser/Parser';
import { SubParserClass } from '../../chord/Parser/subparser';

import CommandParser from './Commands/CommandParser';
import MessageParser from './Messages/MessageParser';
import CollectorParser from './CollectorParser';
import ClientParser from './Client/ClientParser';
import EventParser from './Events/EventParser';
import { CompilationContext } from '../../init/Init';
import DisChordStatementParser from './DisChordStatementParser';

/**
 * Main Orchestrator for DisChord's syntactic analysis.
 * * This class extends the base Parser and delegates the responsibility of parsing 
 * specific structures (Messages, Commands, Events, etc.) to specialized sub-parsers 
 * using a composition-by-delegation pattern.
 */
export class DisChordParser extends Parser<DisChordNodeType, DisChordNode> {
    /**
     * Initializes a new instance of the DisChordParser.
     * @param tokens - The array of tokens generated by the Lexer.
     * @param current - The starting token index (defaults to 0).
     * @param context - The existing context to the DisChordParser.
     */
    constructor (
        tokens: Token<DisChordTokenType>[],
        context: CompilationContext<DisChordNodeType>,
        current: number = 0
    ) {
        super(tokens, current, context);
        this.registerSubParserInstances();
    }

    /**
     * Internal registry of specialized architectural sub-parsers.
     * @type {SubParserClass<DisChordNodeType, DisChordNode>[]}
     * @private
     * @readonly
     * @static
     */
    private static readonly DisChordSubParsers: SubParserClass<DisChordNodeType, DisChordNode>[] = [
        DisChordStatementParser,
        ClientParser,
        EventParser,
        CommandParser,
        MessageParser,
        CollectorParser
    ];

    /**
     * Injects DisChord-specific keywords into the global system 
     * so the Lexer can correctly identify them as tokens.
     * @override
     */
    static override registerGrammar (context: CompilationContext<DisChordNodeType>): void {
        DisChordParser.DisChordSubParsers.forEach(instance => {
            context.keywordsManager.extend(
                instance.keywords.reduce<Record<string, TokenTypeUnion<DisChordNodeType>>>((accumulator, keyword) => {
                    accumulator[keyword] = keyword as TokenTypeUnion<DisChordNodeType>;

                    return accumulator;
                }, {})
            );
        });

        super.registerGrammar(context);
    }

    /**
     * Binds instance-level routing tables for the injected SubParsers into the core execution context.
     * @override
     * @returns {void}
     */
    override registerSubParserInstances(): void {
        DisChordParser.DisChordSubParsers.forEach(instance => {
            this.register(instance);
        });

        super.registerSubParserInstances();
    }

    /**
     * Entry point for custom DisChord statements.
     * Analyzes top-level tokens such as 'encender', 'evento', 'crear', etc.
     * @override
     * @returns The generated ASTNode or null if no match is found.
     */
    override parseCustomStatement(): DisChordASTNode | null {
        const token = this.peek();

        const ParserClass = DisChordParser.DisChordSubParsers.find(SubParser =>
            SubParser.triggerToken !== undefined &&
            SubParser.triggerToken.toUpperCase() === token.type
        );

        if (ParserClass) return new ParserClass(this).parse();

        return null;
    }

    /**
     * Intercepts the statement parsing pipeline to inject the DisChordStatementParser middleware.
     * @override
     * @returns {DisChordASTNode} The processed syntax tree node.
     */
    override parseStatement(): DisChordASTNode {
        return this.get(DisChordStatementParser).parse();
    }
}