import { Token, TokenTypeUnion } from '../../chord/types';
import { DisChordASTNode, DisChordNode, DisChordNodeType, DisChordTokenType } from '../types';

import { Parser } from '../../chord/Parser/parser';
import { SubParserClass } from '../../chord/Parser/subparser';

import CommandParser from './Commands/CommandParser';
import MessageParser from './Messages/MessageParser';
import CollectorParser from './CollectorParser';
import ClientParser from './Client/ClientParser';
import EventParser from './Events/EventParser';
import { DisChordError, ErrorLevel } from '../../ChordError';
import { CompilationContext } from '../../init/Init';

/**
 * Main Orchestrator for DisChord's syntactic analysis.
 * * This class extends the base Parser and delegates the responsibility of parsing 
 * specific structures (Messages, Commands, Events, etc.) to specialized sub-parsers 
 * using a composition-by-delegation pattern.
 */
export class DisChordParser extends Parser<DisChordNodeType, DisChordNode> {
    /**
     * Initializes a new instance of the DisChordParser.
     * @param tokens - The array of tokens generated by the Lexer.
     * @param current - The starting token index (defaults to 0).
     * @param context - The existing context to the DisChordParser.
     */
    constructor (
        tokens: Token<DisChordTokenType>[],
        context: CompilationContext,
        current: number = 0
    ) {
        super(tokens, current, context);
        this.registerGrammar();
    }

    /**
     * Injects DisChord-specific keywords into the global system 
     * so the Lexer can correctly identify them as tokens.
     */
    private registerGrammar(): void {
        const instances: SubParserClass<DisChordNodeType, DisChordNode>[] = [
            ClientParser,
            EventParser,
            CommandParser,
            MessageParser,
            CollectorParser
        ];

        instances.forEach(instance => {
            this.register(instance);

            this.KeywordsManager.extend(
                instance.keywords.reduce<Record<string, TokenTypeUnion<DisChordNodeType>>>((accumulator, keyword) => {
                    accumulator[keyword] = keyword as TokenTypeUnion<DisChordNodeType>;

                    return accumulator;
                }, {})
            );
        });
    }

    /**
     * Entry point for custom DisChord statements.
     * Analyzes top-level tokens such as 'encender', 'evento', 'crear', etc.
     * @override
     * @returns The generated ASTNode or null if no match is found.
     */
    override parseCustomStatement(): DisChordASTNode | null {
        const token = this.peek();

        const ParserClass = DisChordParser.SubParsers.find(SubParser =>
            SubParser.triggerToken !== undefined &&
            SubParser.triggerToken.toUpperCase() === token.type
        );

        if (ParserClass) return new ParserClass(this).parse();

        return null;
    }

    /**
     * Intercepts execution statements. Prioritizes DisChord declarations 
     * before falling back to native Chord statements.
     * @override
     * @returns {DisChordASTNode} The constructed abstract statement node.
     */
    override parseStatement (): DisChordASTNode {
        const token = this.peek();

        switch (token.type) {
            case DisChordTokenType.Crear:
                this.consume(DisChordTokenType.Crear);

                const customStatement = this.parseCustomStatement();
                
                if (!customStatement) throw new DisChordError(
                    ErrorLevel.Parser,
                    `Se esperaba una estructura válida después de 'crear'`,
                    token.location
                ).format();

                return customStatement;
            default:
                return super.parseStatement();
        }
    }
}